name: CI

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy to GitHub Pages
        env:
          MARP_ARGS: "slides/single-responsibility.md -o docs/index.html"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PUBLISH_TO_BRANCH: main
          BASE_URL: https://area73.github.io/talk-css-architecture/
        uses: area73/marp-action@main
